name: Elixir CI

on: push

jobs:
  build:
    services:
      postgres:
        image: postgres:14.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sanity_sync_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Build and test
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        elixir-version: ["1.14"]
        otp-version: ["24", "25"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - name: Install dependencies
        run: mix deps.get
      - name: Compile deps
        run: MIX_ENV=test mix deps.compile
      - name: Compile
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Run tests
        run: mix test --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
